# .github/workflows/rubocop_rspec.yml

name: RuboCop and RSpec

on:
  push:
    branches:
      - development

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RuboCop
      run: bundle exec rubocop
      continue-on-error: true

  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: openai_assistant_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        rails db:create
        rails db:migrate
        rails db:seed

    - name: Run RSpec
      run: bundle exec rspec
