name: Rails server

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run RSpec
      run: bundle exec rspec
