# .github/workflows/rubocop_rspec.yml

name: RuboCop and RSpec

on:
  push:
    branches:
      - development

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RuboCop
      run: bundle exec rubocop
      continue-on-error: true

  rspec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Set up database
      run: |
        echo "test:" > config/database.yml
        echo "  adapter: sqlite3" >> config/database.yml
        echo "  database: db/test.sqlite3" >> config/database.yml

    - name: Install SQLite3
      run: sudo apt-get install sqlite3 libsqlite3-dev

    - name: Run RSpec
      run: bundle exec rspec
